[NO-17457] feat send sns async
chaordic/newoffers-messenger-php pull request #6
Opened 2019-10-17 20:23 UTC by andregaldino

2019-10-18 13:13 UTC, leandrodaf commented on src/Messenger/Clients/Sns.php
> +        $results = \GuzzleHttp\Promise\settle($promises)->wait();
De preferência em fazer os import no inicio do arquivo.

2019-10-18 13:13 UTC, leandrodaf commented on src/Messenger/Clients/Sns.php
> +            $dataToPublish = $this->getDataToPublish($message['topic'], $message['message'], $message['messageAttributes']??[]);
Fazer a quebra de linha nos argumentos.

2019-10-18 18:14 UTC, flaviozantut requested changes

2019-10-18 18:14 UTC, flaviozantut commented on src/Messenger/Clients/Sns.php
> +                if ($error['reason'] instanceof \Aws\Sns\Exception\SnsException) {
```
if ($error['reason'] instanceof \Aws\Sns\Exception\SnsException || $error['reason'] instanceof NoResourceFoundException) {
    $this->createTopic($topic);

    $data = $this->getDataToPublish($topic, $message);
    $result = $this->snsClient->publish($data);
    return $result->get('MessageId');
}
```

2019-10-18 18:14 UTC, flaviozantut commented on src/Messenger/Clients/Sns.php
> +    public function publishAsync(array $data)
faltou adicionar o metodo à interface `Messenger/Contracts/MessengerClient.php`

2019-10-24 14:25 UTC, leandrodaf approved these changes

2019-10-24 17:01 UTC, flaviozantut approved these changes
LGTM

2019-10-24 17:01 UTC, flaviozantut commented on src/Messenger/Contracts/MessengerClient.php
> +    public function publishAsync(array $message): array;
Adcionar um exemplo de mensagem, e mudaria para messages

2019-10-25 15:03 UTC, leandrodaf approved these changes

2019-10-28 18:42 UTC, flaviozantut approved these changes
LGTM

2019-10-28 20:36 UTC, merged